version: '3.3'

services:
  server:
    container_name: server_tests
    restart: unless-stopped
    env_file: ./server/.env
    build:
      context: ./server/
      dockerfile: test.Dockerfile
    logging:
      driver: none
    ports:
      - '8000:8000'
    depends_on:
      - "mongo"
    networks:
      - rt-network-test
    volumes:
      - ./:/server

  client:
    container_name: client_tests
    env_file: ./client/.env
    depends_on:
      - "server"
    build:
      context: ./client/
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - rt-network-test
    volumes:
      - ./:/client

  mongo:
    container_name: mongodb
    image: mongo
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - rt-network-test

networks:
  rt-network-test:
    driver: bridge
