version: "3.3"

services:
  api:
    container_name: api
    restart: unless-stopped
    env_file: ./api/.env
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - rt-network
    volumes:
      - ./:/api

  server:
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - rt-network
    volumes:
      - ./:/server

  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  mongo:
    container_name: db-rt
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/redtetrisdb
    ports:
      - "27017:27017"
    networks:
      - rt-network

networks:
  rt-network:
    driver: bridge

