version: "3.9"

services:
  api:
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./:/app
    depends_on:
      - db

  client:
    container_name: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  db:
    container_name: db-rt
    image: mongo
    # volumes:
    #   - ./data:data/db
    ports:
      - "27017:27017"

