version: "3.9"
services:
  api:
    container_name: api
    restart: unless-stopped
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    # environment:
    #   - SERVER_PORT=8000
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    volumes:
    - ./:/app
    links:
    - mongo
  mongo:
    # env_file: .env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    container_name: mongoDB
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - '27017:27017'